# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'GoogleMaps', '8.4.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '17.4'  # ios.deploymentTarget
  pod 'shared', :path => '../shared'
  # Pods for iosApp
end